### ISSUE TITLE
Help: Filenames can be changed at will

### ISSUE THREAD

**Issue by tarimren-admin** [s1lentq/rechecker#1]
My English is very poor，I hope you understand！
The reality is.
1. the name of the malicious file can be modified at will, with the MD5 value remaining unchanged.
2. whether the MD5 value can be detected in the resources.ini file against。

**Comment by wopox1337** [comment]
No, this is not possible, as the game engine and client require the name of a particular file as well as its MD5 for consistency comparison. ReChecker simply extends this concept by allowing you to check your own list other than the GameDLL, but there is no way to ask the client to search the MD5.
